export { default as Blog } from "./blog/Blog";
export { default as Features } from "./features/Features";
export { default as Footer } from "./footer/Footer";
export { default as Header } from "./header/Header";
export { default as Possibility } from "./possibility/Possibility";
export { default as WhatMN } from "./whatMN/WhatMN";
export { default as ClinetsCarousal } from "./clientscarousal/ClinetsCarousal";
export { default as Testimonials } from "./testimonials/Testimonials";
export { default as Contact } from "./contact/Contact";
